<a href="https://colab.research.google.com/github/RCUELLO72/PythonDataScienceHandbook/blob/master/PDSH_Chapter2_IntroNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

#Introduction to Numpy#

In [0]:
result =0
for i in range(100):
    result += i
print(result)

4950


### Creating arrays from lists

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
matrix = np.array([range(i,i+3) for i in[2,4,6]])
matrix

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
zo = np.zeros((2,4),dtype=float)
zo

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
ons = np.ones((2,3),dtype=int)
ons

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
fop = np.full((3,2),3.141592654)
fop

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [20]:
a1 = np.arange(0,20,2)
a2 = np.linspace(0,1,10)
a3 = np.random.random((2,2))
print(a1)
print(a2)
print(a3)

[ 0  2  4  6  8 10 12 14 16 18]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.88783903 0.22958263]
 [0.30949465 0.35979547]]


In [21]:
a1 = np.empty((2,5))
a1

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

In [22]:
a1[0]

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444])

In [24]:
a1[1,2]

0.7777777777777777

In [31]:
data = pd.read_csv('https://raw.githubusercontent.com/RCUELLO72/PythonDataScienceHandbook/master/president_heights.csv')
heights = data['height(cm)'].values
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [32]:
heights.max()

193