<a href="https://colab.research.google.com/github/RCUELLO72/PythonDataScienceHandbook/blob/master/PDSH_Chapter2_IntroNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Introduction to Numpy#

In [0]:
result =0
for i in range(100):
    result += i
print(result)

4950


### Creating arrays from lists

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
matrix = np.array([range(i,i+3) for i in[2,4,6]])
matrix

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
zo = np.zeros((2,4),dtype=float)
zo

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
ons = np.ones((2,3),dtype=int)
ons

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
fop = np.full((3,2),3.141592654)
fop

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])